slam_toolbox:
  ros__parameters:

    # Frames TF2
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    # Mode
    mode: mapping

    # Résolution et portée
    resolution: 0.05
    max_laser_range: 3.5

    # Fréquences de mise à jour
    map_update_interval: 5.0
    transform_publish_period: 0.02
    minimum_time_interval: 0.5

    # Stabilité
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    use_map_saver: true

    # Solveur mathématique (optimisation de la carte)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_loss_function: None